#pragma once

#include <stddef.h>
#include <stdint.h>
#include <string.h>

namespace owab {

// AI: below section was generated by an AI
static constexpr uint8_t MAX_NAME_BYTES = 32;
static constexpr uint8_t MAX_VERSION_BYTES = 16;

enum ModuleClass : uint8_t {
  MODULE_SMART_SHADE = 1,
  MODULE_BATTERY = 2,
  MODULE_SENSOR = 3
};

enum TlvType : uint8_t {
  TLV_MODULE_CLASS = 0x01,
  TLV_LED_COUNT = 0x02,
  TLV_TOUCH = 0x03,
  TLV_NAME = 0x04,
  TLV_BATTERY_MV = 0x10,
  TLV_BATTERY_PERCENT = 0x11,
  TLV_CHARGING = 0x12,
  TLV_TEMPERATURE_DECI_C = 0x13,
  TLV_STATUS = 0x14,
  TLV_HW_VERSION = 0x20,
  TLV_FW_VERSION = 0x21
};

enum ParseError : uint8_t {
  PARSE_OK = 0,
  PARSE_TOO_SHORT,
  PARSE_BAD_MAGIC,
  PARSE_BAD_VERSION,
  PARSE_BAD_LENGTH,
  PARSE_BAD_CRC,
  PARSE_DUPLICATE_TLV,
  PARSE_BAD_TLV_LENGTH,
  PARSE_BAD_VALUE,
  PARSE_MISSING_REQUIRED_TLV,
  PARSE_FORBIDDEN_TLV,
  PARSE_LEGACY_DISABLED
};

enum TelemetryField : uint8_t {
  TELEMETRY_MILLIVOLTS = 1U << 0,
  TELEMETRY_PERCENT = 1U << 1,
  TELEMETRY_CHARGING = 1U << 2,
  TELEMETRY_TEMPERATURE = 1U << 3,
  TELEMETRY_STATUS = 1U << 4
};

struct DescriptorData {
  uint8_t moduleClass = 0;
  uint16_t ledCount = 0;
  bool touch = true;
  bool hasLedCount = false;
  bool hasTouch = false;
  char name[MAX_NAME_BYTES + 1] = {0};
  char hardwareVersion[MAX_VERSION_BYTES + 1] = {0};
  char firmwareVersion[MAX_VERSION_BYTES + 1] = {0};
};

struct TelemetryData {
  uint8_t fields = 0;
  bool framed = false;
  uint8_t sequence = 0;
  uint16_t millivolts = 0;
  uint8_t percent = 0;
  bool charging = false;
  int16_t temperatureDeciC = 0;
  uint16_t status = 0;
};

inline uint16_t readU16LE(const uint8_t *data) {
  return uint16_t(data[0]) | (uint16_t(data[1]) << 8);
}

inline uint16_t crc16CcittFalse(const uint8_t *data, size_t len) {
  uint16_t crc = 0xFFFF;
  for (size_t i = 0; i < len; i++) {
    crc ^= uint16_t(data[i]) << 8;
    for (uint8_t bit = 0; bit < 8; bit++) {
      crc = (crc & 0x8000U) ? uint16_t((crc << 1) ^ 0x1021U) : uint16_t(crc << 1);
    }
  }
  return crc;
}

inline bool intervalDue(uint32_t now, uint32_t lastAttempt, uint32_t interval) {
  return lastAttempt == 0 || uint32_t(now - lastAttempt) >= interval;
}

inline bool isValidUtf8Text(const uint8_t *data, size_t len) {
  size_t pos = 0;
  while (pos < len) {
    const uint8_t first = data[pos++];
    if (first == 0 || first < 0x20 || first == 0x7F) return false;
    if (first < 0x80) continue;

    uint8_t remaining = 0;
    uint32_t codepoint = 0;
    uint32_t minimum = 0;
    if ((first & 0xE0) == 0xC0) {
      remaining = 1;
      codepoint = first & 0x1F;
      minimum = 0x80;
    } else if ((first & 0xF0) == 0xE0) {
      remaining = 2;
      codepoint = first & 0x0F;
      minimum = 0x800;
    } else if ((first & 0xF8) == 0xF0) {
      remaining = 3;
      codepoint = first & 0x07;
      minimum = 0x10000;
    } else {
      return false;
    }

    if (pos + remaining > len) return false;
    while (remaining--) {
      const uint8_t next = data[pos++];
      if ((next & 0xC0) != 0x80) return false;
      codepoint = (codepoint << 6) | (next & 0x3F);
    }
    if (codepoint < minimum || codepoint > 0x10FFFF
        || (codepoint >= 0xD800 && codepoint <= 0xDFFF)) return false;
  }
  return true;
}

inline const char *parseErrorName(ParseError error) {
  switch (error) {
    case PARSE_OK: return "ok";
    case PARSE_TOO_SHORT: return "too_short";
    case PARSE_BAD_MAGIC: return "bad_magic";
    case PARSE_BAD_VERSION: return "bad_version";
    case PARSE_BAD_LENGTH: return "bad_length";
    case PARSE_BAD_CRC: return "bad_crc";
    case PARSE_DUPLICATE_TLV: return "duplicate_tlv";
    case PARSE_BAD_TLV_LENGTH: return "bad_tlv_length";
    case PARSE_BAD_VALUE: return "bad_value";
    case PARSE_MISSING_REQUIRED_TLV: return "missing_required_tlv";
    case PARSE_FORBIDDEN_TLV: return "forbidden_tlv";
    case PARSE_LEGACY_DISABLED: return "legacy_disabled";
    default: return "unknown";
  }
}

inline bool copyText(char *destination, size_t destinationSize, const uint8_t *source, uint8_t length) {
  if (length == 0 || length >= destinationSize) return false;
  if (!isValidUtf8Text(source, length)) return false;
  memcpy(destination, source, length);
  destination[length] = 0;
  return true;
}

inline bool parseDescriptorTlvs(const uint8_t *payload, uint8_t len, uint16_t maxLedCount,
                                DescriptorData &descriptor, ParseError &error) {
  DescriptorData parsed;
  uint32_t seen = 0;
  uint8_t pos = 0;

  while (pos + 2 <= len) {
    const uint8_t type = payload[pos++];
    const uint8_t valueLen = payload[pos++];
    if (uint16_t(pos) + valueLen > len) {
      error = PARSE_BAD_LENGTH;
      return false;
    }

    const uint8_t *value = payload + pos;
    uint8_t seenBit = 0;
    switch (type) {
      case TLV_MODULE_CLASS: seenBit = 1U << 0; break;
      case TLV_LED_COUNT: seenBit = 1U << 1; break;
      case TLV_TOUCH: seenBit = 1U << 2; break;
      case TLV_NAME: seenBit = 1U << 3; break;
      case TLV_HW_VERSION: seenBit = 1U << 4; break;
      case TLV_FW_VERSION: seenBit = 1U << 5; break;
      case TLV_BATTERY_MV:
      case TLV_BATTERY_PERCENT:
      case TLV_CHARGING:
      case TLV_TEMPERATURE_DECI_C:
      case TLV_STATUS:
        error = PARSE_FORBIDDEN_TLV;
        return false;
      default:
        break;
    }

    if (seenBit && (seen & seenBit)) {
      error = PARSE_DUPLICATE_TLV;
      return false;
    }
    seen |= seenBit;

    switch (type) {
      case TLV_MODULE_CLASS:
        if (valueLen != 1) { error = PARSE_BAD_TLV_LENGTH; return false; }
        if (value[0] < MODULE_SMART_SHADE || value[0] > MODULE_SENSOR) { error = PARSE_BAD_VALUE; return false; }
        parsed.moduleClass = value[0];
        break;
      case TLV_LED_COUNT:
        if (valueLen != 2) { error = PARSE_BAD_TLV_LENGTH; return false; }
        parsed.ledCount = readU16LE(value);
        parsed.hasLedCount = true;
        break;
      case TLV_TOUCH:
        if (valueLen != 1) { error = PARSE_BAD_TLV_LENGTH; return false; }
        if (value[0] > 1) { error = PARSE_BAD_VALUE; return false; }
        parsed.touch = value[0] != 0;
        parsed.hasTouch = true;
        break;
      case TLV_NAME:
        if (!copyText(parsed.name, sizeof(parsed.name), value, valueLen)) { error = PARSE_BAD_TLV_LENGTH; return false; }
        break;
      case TLV_HW_VERSION:
        if (!copyText(parsed.hardwareVersion, sizeof(parsed.hardwareVersion), value, valueLen)) { error = PARSE_BAD_TLV_LENGTH; return false; }
        break;
      case TLV_FW_VERSION:
        if (!copyText(parsed.firmwareVersion, sizeof(parsed.firmwareVersion), value, valueLen)) { error = PARSE_BAD_TLV_LENGTH; return false; }
        break;
      default:
        break;
    }

    pos += valueLen;
  }

  if (pos != len) { error = PARSE_BAD_LENGTH; return false; }
  if (!(seen & (1U << 0))) { error = PARSE_MISSING_REQUIRED_TLV; return false; }
  if (parsed.moduleClass == MODULE_SMART_SHADE) {
    if (!parsed.hasLedCount) { error = PARSE_MISSING_REQUIRED_TLV; return false; }
    if (parsed.ledCount == 0 || parsed.ledCount > maxLedCount) { error = PARSE_BAD_VALUE; return false; }
  }

  descriptor = parsed;
  error = PARSE_OK;
  return true;
}

inline bool parseDescriptor(const uint8_t *payload, uint8_t len, uint16_t maxLedCount,
                            DescriptorData &descriptor, ParseError &error) {
  if (len < 8) { error = PARSE_TOO_SHORT; return false; }
  if (memcmp(payload, "WLA1", 4) != 0) { error = PARSE_BAD_MAGIC; return false; }
  if (payload[4] != 1) { error = PARSE_BAD_VERSION; return false; }

  const uint8_t tlvLen = payload[5];
  if (uint16_t(tlvLen) + 8U != len) { error = PARSE_BAD_LENGTH; return false; }
  if (readU16LE(payload + 6 + tlvLen) != crc16CcittFalse(payload, 6 + tlvLen)) {
    error = PARSE_BAD_CRC;
    return false;
  }
  return parseDescriptorTlvs(payload + 6, tlvLen, maxLedCount, descriptor, error);
}

inline bool parseTelemetryTlvs(const uint8_t *payload, uint8_t len, TelemetryData &telemetry, ParseError &error) {
  TelemetryData parsed = telemetry;
  parsed.fields = 0;
  uint8_t pos = 0;

  while (pos + 2 <= len) {
    const uint8_t type = payload[pos++];
    const uint8_t valueLen = payload[pos++];
    if (uint16_t(pos) + valueLen > len) { error = PARSE_BAD_LENGTH; return false; }

    const uint8_t *value = payload + pos;
    uint8_t field = 0;
    switch (type) {
      case TLV_BATTERY_MV: field = TELEMETRY_MILLIVOLTS; break;
      case TLV_BATTERY_PERCENT: field = TELEMETRY_PERCENT; break;
      case TLV_CHARGING: field = TELEMETRY_CHARGING; break;
      case TLV_TEMPERATURE_DECI_C: field = TELEMETRY_TEMPERATURE; break;
      case TLV_STATUS: field = TELEMETRY_STATUS; break;
      case TLV_MODULE_CLASS:
      case TLV_LED_COUNT:
      case TLV_TOUCH:
      case TLV_NAME:
      case TLV_HW_VERSION:
      case TLV_FW_VERSION:
        error = PARSE_FORBIDDEN_TLV;
        return false;
      default:
        break;
    }

    if (field && (parsed.fields & field)) { error = PARSE_DUPLICATE_TLV; return false; }
    parsed.fields |= field;

    switch (type) {
      case TLV_BATTERY_MV:
        if (valueLen != 2) { error = PARSE_BAD_TLV_LENGTH; return false; }
        parsed.millivolts = readU16LE(value);
        break;
      case TLV_BATTERY_PERCENT:
        if (valueLen != 1) { error = PARSE_BAD_TLV_LENGTH; return false; }
        if (value[0] > 100) { error = PARSE_BAD_VALUE; return false; }
        parsed.percent = value[0];
        break;
      case TLV_CHARGING:
        if (valueLen != 1) { error = PARSE_BAD_TLV_LENGTH; return false; }
        if (value[0] > 1) { error = PARSE_BAD_VALUE; return false; }
        parsed.charging = value[0] != 0;
        break;
      case TLV_TEMPERATURE_DECI_C:
        if (valueLen != 2) { error = PARSE_BAD_TLV_LENGTH; return false; }
        parsed.temperatureDeciC = int16_t(readU16LE(value));
        break;
      case TLV_STATUS:
        if (valueLen != 2) { error = PARSE_BAD_TLV_LENGTH; return false; }
        parsed.status = readU16LE(value);
        break;
      default:
        break;
    }

    pos += valueLen;
  }

  if (pos != len) { error = PARSE_BAD_LENGTH; return false; }
  if (parsed.fields == 0) { error = PARSE_MISSING_REQUIRED_TLV; return false; }
  telemetry = parsed;
  error = PARSE_OK;
  return true;
}

inline bool parseTelemetry(const uint8_t *payload, uint8_t len, bool allowLegacy,
                           TelemetryData &telemetry, ParseError &error) {
  if (len >= 4 && memcmp(payload, "WLT1", 4) == 0) {
    if (len < 10) { error = PARSE_TOO_SHORT; return false; }
    if (payload[4] != 1) { error = PARSE_BAD_VERSION; return false; }
    if (payload[5] != 1) { error = PARSE_BAD_VALUE; return false; }
    const uint8_t tlvLen = payload[7];
    if (uint16_t(tlvLen) + 10U != len) { error = PARSE_BAD_LENGTH; return false; }
    if (readU16LE(payload + 8 + tlvLen) != crc16CcittFalse(payload, 8 + tlvLen)) {
      error = PARSE_BAD_CRC;
      return false;
    }

    TelemetryData parsed;
    parsed.framed = true;
    parsed.sequence = payload[6];
    if (!parseTelemetryTlvs(payload + 8, tlvLen, parsed, error)) return false;
    telemetry = parsed;
    return true;
  }

  if (!allowLegacy) { error = PARSE_LEGACY_DISABLED; return false; }
  TelemetryData parsed;
  parsed.framed = false;
  if (!parseTelemetryTlvs(payload, len, parsed, error)) return false;
  telemetry = parsed;
  return true;
}

// AI: end
} // namespace owab
