'use strict';

const assert = require('node:assert/strict');
const { describe, it } = require('node:test');
const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const usermodDir = __dirname;
const source = fs.readFileSync(path.join(usermodDir, 'onewire_accessory_bus.cpp'), 'utf8');
const protocol = fs.readFileSync(path.join(usermodDir, 'onewire_accessory_protocol.h'), 'utf8');
const manifest = fs.readFileSync(path.join(usermodDir, 'library.json'), 'utf8');
const smokeTest = fs.readFileSync(path.join(usermodDir, 'smoke-test.js'), 'utf8');

function sectionBetween(startNeedle, endNeedle) {
  const start = source.indexOf(startNeedle);
  assert.notEqual(start, -1, `missing start marker: ${startNeedle}`);
  const end = source.indexOf(endNeedle, start);
  assert.notEqual(end, -1, `missing end marker: ${endNeedle}`);
  return source.slice(start, end);
}

function pageHtml() {
  const marker = 'const char OneWireAccessoryBusUsermod::PAGE_ONEWIRE[] PROGMEM = R"=====(';
  const start = source.indexOf(marker);
  assert.notEqual(start, -1, 'missing PAGE_ONEWIRE raw string');
  const bodyStart = start + marker.length;
  const end = source.indexOf(')=====";', bodyStart);
  assert.notEqual(end, -1, 'missing PAGE_ONEWIRE raw string terminator');
  return source.slice(bodyStart, end);
}

function nativeCompilerFlags() {
  const flags = ['-std=c++11', '-Wall', '-Wextra', '-Werror', '-pedantic'];
  if (process.platform !== 'darwin') return flags;

  const sdk = spawnSync('xcrun', ['--show-sdk-path'], { encoding: 'utf8' });
  assert.equal(sdk.status, 0, sdk.stderr || sdk.stdout || 'xcrun could not locate the macOS SDK');
  return [...flags, '-isysroot', sdk.stdout.trim()];
}

// AI: below section was generated by an AI
describe('OneWire Accessory Bus executable and source contracts', () => {
  it('compiles and executes the native protocol test suite', () => {
    for (const sanitized of [false, true]) {
      const output = path.join(os.tmpdir(), `owab-protocol-${process.pid}-${sanitized ? 'san' : 'plain'}`);
      const flags = nativeCompilerFlags();
      if (sanitized) flags.push('-fsanitize=address,undefined', '-fno-omit-frame-pointer');
      const compile = spawnSync('c++', [
        ...flags,
        path.join(usermodDir, 'onewire_accessory_protocol.test.cpp'),
        '-o', output
      ], { encoding: 'utf8' });
      assert.equal(compile.status, 0, compile.stderr || compile.stdout);

      const run = spawnSync(output, [], { encoding: 'utf8' });
      fs.rmSync(output, { force: true });
      assert.equal(run.status, 0, run.stderr || run.stdout);
      assert.match(run.stdout, /protocol tests passed/);
    }
  });

  it('keeps native tests out of firmware builds', () => {
    assert.match(source, /#include "onewire_accessory_protocol\.h"/);
    assert.match(manifest, /-<\*\.test\.cpp>/);
  });

  it('strictly separates descriptor and telemetry TLVs', () => {
    assert.match(protocol, /parseDescriptorTlvs/);
    assert.match(protocol, /parseTelemetryTlvs/);
    assert.match(protocol, /PARSE_FORBIDDEN_TLV/);
    assert.match(protocol, /PARSE_DUPLICATE_TLV/);
    assert.match(protocol, /PARSE_LEGACY_DISABLED/);
    assert.match(source, /allowLegacyTelemetry = false/);
    assert.match(source, /battery\.validFields \|= telemetry\.fields/);
    assert.doesNotMatch(sectionBetween('bool parseTelemetryPayload', 'bool readAccessoryPayload'), /ledCount|touch|name/);
  });

  it('uses a dedicated ESP32 worker for complete scans and bounded smart reads', () => {
    const service = sectionBetween('void serviceSmartDevices()', 'void commitPendingDevices()');
    const worker = sectionBetween('static void wireWorkerTask', 'bool initializeWireWorker');
    assert.match(service, /SMART_SERVICE_INTERVAL_MS/);
    assert.match(service, /smartCursor/);
    assert.match(service, /queueWireJob\(job\)/);
    assert.match(worker, /xQueueReceive/);
    assert.match(worker, /while \(workerBus\.search\(rom\)\)/);
    assert.match(worker, /MAX_SEARCH_ITERATIONS/);
    assert.match(worker, /result\.romCount >= MAX_DEVICES/);
    assert.match(worker, /taskYIELD\(\)/);
    assert.match(source, /xTaskCreatePinnedToCore\(wireWorkerTask, "owab-wire"/);
    assert.match(source, /const uint8_t maximumLength = operation == WIRE_READ_DESCRIPTOR \? MAX_DESCRIPTOR_BYTES : 48/);
    assert.match(source, /DESCRIPTOR_RETRY_INTERVAL_MS = 10000/);
    assert.match(source, /SMART_BUSY_BYTE = 0xFF/);
    assert.match(source, /SMART_READY_RETRIES = 5/);
    assert.doesNotMatch(worker, /SCAN_BUDGET_US|50\s*\*\s*1000/);
  });

  it('only enrolls stable smart shades after explicit opt-in or an existing profile', () => {
    const applySmart = sectionBetween('void applySmartShadeAsProfile', 'bool parseDescriptor');
    assert.match(source, /autoEnrollSmartShades = false/);
    assert.match(source, /autoUpdateSmartProfiles = false/);
    assert.match(source, /SMART_DESCRIPTOR_CONFIRMATIONS = 3/);
    assert.match(applySmart, /!device\.descriptorValid/);
    assert.match(applySmart, /!autoEnrollSmartShades \|\| device\.descriptorStableReads < SMART_DESCRIPTOR_CONFIRMATIONS/);
    assert.match(applySmart, /!autoUpdateSmartProfiles \|\| device\.descriptorStableReads < SMART_DESCRIPTOR_CONFIRMATIONS/);
    assert.match(applySmart, /smartProfileUpdatedThisBoot\(device\.romStr\)/);
    assert.match(applySmart, /markSmartProfileUpdatedThisBoot\(device\.romStr\)/);
    assert.match(source, /SMART_PROFILE_WRITE_INTERVAL_MS = 300000/);
  });

  it('models clean empty and electrical scan failures separately', () => {
    const scanResult = sectionBetween('void processScanResult', '#ifdef ARDUINO_ARCH_ESP32');
    assert.match(source, /BUS_EMPTY_CLEAN/);
    assert.match(source, /BUS_STUCK_LOW/);
    assert.match(source, /BUS_PRESENCE_INVALID/);
    assert.match(source, /BUS_CRC_ERROR/);
    assert.match(source, /BUS_SEARCH_LIMIT/);
    assert.match(source, /BUS_OVERFLOW/);
    assert.match(scanResult, /result\.iterationLimit/);
    assert.match(scanResult, /result\.overflow/);
    assert.doesNotMatch(source, /BUS_BUDGET_EXCEEDED|SCAN_BUDGET_US/);
    assert.match(source, /busStateKnown && busHealth == BUS_EMPTY_CLEAN/);
  });

  it('protects manual scans and rate limits them', () => {
    const readState = sectionBetween('void readFromJsonState', '#ifndef WLED_DISABLE_MQTT');
    assert.match(source, /return \(top\[F\("scan"\)\] \| false\)/);
    assert.match(source, /MANUAL_SCAN_RATE_LIMIT_MS = 1000/);
    assert.ok(readState.indexOf('requireWriteAllowed(root, top)') < readState.indexOf('lastManualScanRequestMs'));
  });

  it('validates API values without clamping invalid commands', () => {
    const validation = sectionBetween('bool validateProfileSet', 'bool handleProfileSet');
    assert.match(validation, /invalid_led_count/);
    assert.match(validation, /invalid_input_mode/);
    assert.match(validation, /invalid_button/);
    assert.match(validation, /invalid_ledmap/);
    assert.match(validation, /invalid_rom/);
    assert.match(source, /commandCode/);
    assert.match(source, /commandMessage/);
  });

  it('deduplicates loaded profiles and reports config overflow', () => {
    const config = sectionBetween('bool readFromConfig', 'void appendConfigData');
    assert.match(config, /findProfile\(normalized\) >= 0/);
    assert.match(config, /profileConfigDuplicates\+\+/);
    assert.match(config, /profileConfigOverflow = true/);
    assert.match(source, /profileConfigOverflow/);
  });

  it('keeps every documented input mode and restores inherited hardware once', () => {
    const html = pageHtml();
    for (const mode of ['inherit', 'disabled', 'buttonLow', 'buttonHigh', 'touch', 'touchSwitch']) {
      assert.match(source, new RegExp(`"${mode}"`));
      assert.match(html, new RegExp(`value="${mode}"`));
    }
    const configure = sectionBetween('void configureActiveProfileInput()', 'bool readManagedButton');
    assert.match(configure, /configuredProfileIndex == activeProfile/);
    assert.match(configure, /restoreManagedInputHardware\(\)/);
  });

  it('serializes ESP32 state shared with asynchronous callbacks', () => {
    assert.match(source, /xSemaphoreCreateMutex\(\)/);
    assert.match(source, /xSemaphoreTake\(stateMutex, waitTicks\)/);
    assert.match(source, /STATE_LOCK_WAIT = portMAX_DELAY/);
    assert.match(sectionBetween('void loop() override', 'bool handleButton'), /StateGuard stateGuard/);
    assert.match(sectionBetween('bool handleButton', 'void addToJsonInfo'), /StateGuard stateGuard/);
    assert.match(sectionBetween('void addToJsonState', 'void readFromJsonState'), /StateGuard stateGuard/);
    assert.match(sectionBetween('void readFromJsonState', '#ifndef WLED_DISABLE_MQTT'), /StateGuard stateGuard/);
  });

  it('preserves a newer apply target until the active transaction is verified', () => {
    const verify = sectionBetween('void refreshApplyStatus()', 'void debugPrintDeviceList');
    const apply = sectionBetween('void applyActiveProfile()', 'void configureActiveProfileInput()');
    assert.doesNotMatch(verify, /if \(applyRequested\) return/);
    assert.match(apply, /if \(applyPhase != APPLY_IDLE\)/);
    assert.match(apply, /new target pending/);
    assert.doesNotMatch(apply, /applyRequested = false;[\s\S]{0,160}new target pending/);
    assert.match(source, /applyRequested = autoApplyProfile/);
  });

  it('supports runtime OneWire pin and pull-up reinitialization', () => {
    assert.match(source, /void teardownOneWire\(\)/);
    assert.match(source, /bool initializeOneWire\(\)/);
    assert.match(source, /void reinitializeOneWireIfRequested\(\)/);
    assert.match(source, /activeOneWirePin/);
    assert.match(source, /rebootRequired/);
  });

  it('applies only bounded digital buses and verifies rollback', () => {
    const capture = sectionBetween('bool captureCurrentBus', 'bool scheduleBusLength');
    const verify = sectionBetween('void refreshApplyStatus()', 'void debugPrintDeviceList');
    assert.match(capture, /current->isPlaceholder\(\)/);
    assert.match(capture, /!current->isDigital\(\)/);
    assert.match(capture, /uint32_t\(current->getStart\(\)\) \+ ledCount > MAX_LEDS/);
    assert.match(capture, /APPLY_HEAP_MARGIN_BYTES/);
    assert.match(source, /effectiveLedmap = ledmap == -1 \? static_cast<int8_t>\(currentBus\.ledmap\)/);
    assert.match(verify, /APPLY_WAIT_ROLLBACK/);
    assert.match(verify, /apply failed; rolled back/);
  });

  it('uses bounded reusable MQTT storage and retries failed discovery', () => {
    assert.match(source, /StaticJsonDocument<4096> mqttStatusDocument/);
    assert.match(source, /mqttStatusDocument\.clear\(\)/);
    assert.match(source, /doc\.overflowed\(\)/);
    assert.match(source, /mqttDiscoveryPending = !success/);
    assert.match(source, /availability_topic/);
    assert.match(source, /state_class/);
    assert.match(source, /device_overflow.*true/);
  });

  it('does not republish stale individual telemetry fields', () => {
    const publish = sectionBetween('void publishBatteryTelemetry', 'bool publishHomeAssistantSensor');
    assert.match(source, /telemetryFieldAgeMs/);
    assert.match(source, /uint32_t\(now - updated\)/);
    assert.match(source, /telemetryAnyStale/);
    assert.ok((publish.match(/!telemetryFieldStale/g) || []).length >= 5);
    assert.match(publish, /battery_stale/);
  });

  it('uses runtime UI limits, accessible tables, confirmation, and transient PIN storage', () => {
    const html = pageHtml();
    assert.match(source, /maxLedsPerBus/);
    assert.match(source, /maxButtons/);
    assert.match(source, /maxLedmaps/);
    assert.match(html, /aria-live="polite"/);
    assert.match(html, /<caption>/);
    assert.match(html, /scope="col"/);
    assert.match(html, /confirm\('Delete this shade profile\?'\)/);
    assert.match(html, /async function runAction/);
    assert.doesNotMatch(html, /sessionStorage/);
    assert.doesNotMatch(html, /<a[^>]*><button/);
  });

  it('requires meaningful stable-state hardware smoke tests', () => {
    assert.match(smokeTest, /Node\.js 18 or newer/);
    assert.match(smokeTest, /OWAB_ALLOW_EMPTY/);
    assert.match(smokeTest, /OWAB_SETTINGS_PIN/);
    assert.match(smokeTest, /initialScanCount/);
    assert.match(smokeTest, /scanCount > initialScanCount/);
    assert.match(smokeTest, /expected ROM .* was not detected after a fresh stable scan/);
    assert.match(smokeTest, /busHealth/);
  });
});
// AI: end
