#include "onewire_accessory_protocol.h"

#include <assert.h>
#include <stdio.h>
#include <string.h>

// AI: below test suite was generated by an AI
static void appendCrc(uint8_t *frame, size_t payloadLength) {
  const uint16_t crc = owab::crc16CcittFalse(frame, payloadLength);
  frame[payloadLength] = uint8_t(crc);
  frame[payloadLength + 1] = uint8_t(crc >> 8);
}

static void testCrcVector() {
  const uint8_t vector[] = "123456789";
  assert(owab::crc16CcittFalse(vector, 9) == 0x29B1);
}

static void testDescriptorValidation() {
  uint8_t frame[] = {
    'W', 'L', 'A', '1', 1, 14,
    owab::TLV_MODULE_CLASS, 1, owab::MODULE_SMART_SHADE,
    owab::TLV_LED_COUNT, 2, 101, 0,
    owab::TLV_TOUCH, 1, 1,
    owab::TLV_NAME, 2, 'O', 'K',
    0, 0
  };
  appendCrc(frame, sizeof(frame) - 2);

  owab::DescriptorData descriptor;
  owab::ParseError error = owab::PARSE_OK;
  assert(owab::parseDescriptor(frame, sizeof(frame), 2048, descriptor, error));
  assert(error == owab::PARSE_OK);
  assert(descriptor.moduleClass == owab::MODULE_SMART_SHADE);
  assert(descriptor.ledCount == 101);
  assert(descriptor.touch);
  assert(strcmp(descriptor.name, "OK") == 0);

  uint8_t duplicate[] = {
    'W', 'L', 'A', '1', 1, 10,
    owab::TLV_MODULE_CLASS, 1, owab::MODULE_SMART_SHADE,
    owab::TLV_MODULE_CLASS, 1, owab::MODULE_SMART_SHADE,
    owab::TLV_LED_COUNT, 2, 10, 0,
    0, 0
  };
  appendCrc(duplicate, sizeof(duplicate) - 2);
  assert(!owab::parseDescriptor(duplicate, sizeof(duplicate), 2048, descriptor, error));
  assert(error == owab::PARSE_DUPLICATE_TLV);
}

static void testExplicitCrcFailures() {
  uint8_t descriptorFrame[] = {
    'W', 'L', 'A', '1', 1, 7,
    owab::TLV_MODULE_CLASS, 1, owab::MODULE_SMART_SHADE,
    owab::TLV_LED_COUNT, 2, 14, 0,
    0, 0
  };
  appendCrc(descriptorFrame, sizeof(descriptorFrame) - 2);
  descriptorFrame[8] ^= 0x01;
  owab::DescriptorData descriptor;
  owab::ParseError error = owab::PARSE_OK;
  assert(!owab::parseDescriptor(descriptorFrame, sizeof(descriptorFrame), 2048, descriptor, error));
  assert(error == owab::PARSE_BAD_CRC);

  uint8_t telemetryFrame[] = {
    'W', 'L', 'T', '1', 1, 1, 7, 3,
    owab::TLV_BATTERY_PERCENT, 1, 60,
    0, 0
  };
  appendCrc(telemetryFrame, sizeof(telemetryFrame) - 2);
  telemetryFrame[10] ^= 0x01;
  owab::TelemetryData telemetry;
  assert(!owab::parseTelemetry(telemetryFrame, sizeof(telemetryFrame), false, telemetry, error));
  assert(error == owab::PARSE_BAD_CRC);
}

static void testDescriptorRejectsTelemetryAndBadBounds() {
  uint8_t forbidden[] = {
    'W', 'L', 'A', '1', 1, 6,
    owab::TLV_MODULE_CLASS, 1, owab::MODULE_BATTERY,
    owab::TLV_BATTERY_PERCENT, 1, 50,
    0, 0
  };
  appendCrc(forbidden, sizeof(forbidden) - 2);
  owab::DescriptorData descriptor;
  owab::ParseError error = owab::PARSE_OK;
  assert(!owab::parseDescriptor(forbidden, sizeof(forbidden), 2048, descriptor, error));
  assert(error == owab::PARSE_FORBIDDEN_TLV);

  uint8_t tooMany[] = {
    'W', 'L', 'A', '1', 1, 7,
    owab::TLV_MODULE_CLASS, 1, owab::MODULE_SMART_SHADE,
    owab::TLV_LED_COUNT, 2, 0x01, 0x08,
    0, 0
  };
  appendCrc(tooMany, sizeof(tooMany) - 2);
  assert(!owab::parseDescriptor(tooMany, sizeof(tooMany), 1024, descriptor, error));
  assert(error == owab::PARSE_BAD_VALUE);
}

static void testDescriptorRejectsInvalidUtf8() {
  uint8_t invalidUtf8[] = {
    'W', 'L', 'A', '1', 1, 8,
    owab::TLV_MODULE_CLASS, 1, owab::MODULE_BATTERY,
    owab::TLV_NAME, 3, 0xE2, 0x82, 'X',
    0, 0
  };
  appendCrc(invalidUtf8, sizeof(invalidUtf8) - 2);
  owab::DescriptorData descriptor;
  owab::ParseError error = owab::PARSE_OK;
  assert(!owab::parseDescriptor(invalidUtf8, sizeof(invalidUtf8), 2048, descriptor, error));
  assert(error == owab::PARSE_BAD_TLV_LENGTH);

  const uint8_t validUtf8[] = {'T', 'e', 's', 't', ' ', 0xE2, 0x82, 0xAC};
  assert(owab::isValidUtf8Text(validUtf8, sizeof(validUtf8)));
}

static void testFramedTelemetryAllowlist() {
  uint8_t frame[] = {
    'W', 'L', 'T', '1', 1, 1, 42, 10,
    owab::TLV_BATTERY_MV, 2, 0x3C, 0x0F,
    owab::TLV_BATTERY_PERCENT, 1, 75,
    owab::TLV_CHARGING, 1, 1,
    0, 0
  };
  appendCrc(frame, sizeof(frame) - 2);

  owab::TelemetryData telemetry;
  owab::ParseError error = owab::PARSE_OK;
  assert(owab::parseTelemetry(frame, sizeof(frame), false, telemetry, error));
  assert(telemetry.framed);
  assert(telemetry.sequence == 42);
  assert(telemetry.fields == (owab::TELEMETRY_MILLIVOLTS | owab::TELEMETRY_PERCENT | owab::TELEMETRY_CHARGING));
  assert(telemetry.millivolts == 3900);
  assert(telemetry.percent == 75);
  assert(telemetry.charging);

  frame[8] = owab::TLV_LED_COUNT;
  appendCrc(frame, sizeof(frame) - 2);
  assert(!owab::parseTelemetry(frame, sizeof(frame), false, telemetry, error));
  assert(error == owab::PARSE_FORBIDDEN_TLV);
}

static void testPartialTelemetryAndSequenceWrap() {
  uint8_t frame[] = {
    'W', 'L', 'T', '1', 1, 1, 255, 4,
    owab::TLV_BATTERY_MV, 2, 0xA0, 0x0F,
    0, 0
  };
  appendCrc(frame, sizeof(frame) - 2);
  owab::TelemetryData telemetry;
  telemetry.percent = 88;
  telemetry.fields = owab::TELEMETRY_PERCENT;
  owab::ParseError error = owab::PARSE_OK;
  assert(owab::parseTelemetry(frame, sizeof(frame), false, telemetry, error));
  assert(telemetry.sequence == 255);
  assert(telemetry.fields == owab::TELEMETRY_MILLIVOLTS);
  assert(telemetry.millivolts == 4000);

  frame[6] = 0;
  appendCrc(frame, sizeof(frame) - 2);
  assert(owab::parseTelemetry(frame, sizeof(frame), false, telemetry, error));
  assert(telemetry.sequence == 0);
  assert(telemetry.fields == owab::TELEMETRY_MILLIVOLTS);
}

static void testAllFrameLengthsAndDeterministicInput() {
  uint8_t bytes[UINT8_MAX] = {0};
  uint32_t state = 0x6D2B79F5U;
  for (size_t i = 0; i < sizeof(bytes); i++) {
    state = state * 1664525U + 1013904223U;
    bytes[i] = uint8_t(state >> 24);
  }

  for (uint16_t length = 0; length <= UINT8_MAX; length++) {
    owab::DescriptorData descriptor;
    owab::TelemetryData telemetry;
    owab::ParseError error = owab::PARSE_OK;
    (void)owab::parseDescriptor(bytes, uint8_t(length), 2048, descriptor, error);
    (void)owab::parseTelemetry(bytes, uint8_t(length), false, telemetry, error);
  }

  uint8_t descriptorFrame[] = {
    'W', 'L', 'A', '1', 1, 7,
    owab::TLV_MODULE_CLASS, 1, owab::MODULE_SMART_SHADE,
    owab::TLV_LED_COUNT, 2, 14, 0,
    0, 0
  };
  appendCrc(descriptorFrame, sizeof(descriptorFrame) - 2);
  for (uint16_t advertised = 0; advertised <= UINT8_MAX; advertised++) {
    descriptorFrame[5] = uint8_t(advertised);
    owab::DescriptorData descriptor;
    owab::ParseError error = owab::PARSE_OK;
    const bool valid = owab::parseDescriptor(descriptorFrame, sizeof(descriptorFrame), 2048, descriptor, error);
    assert(valid == (advertised == 7));
  }
}

static void testLegacyTelemetryPolicy() {
  const uint8_t legacy[] = {owab::TLV_STATUS, 2, 2, 0};
  owab::TelemetryData telemetry;
  owab::ParseError error = owab::PARSE_OK;
  assert(!owab::parseTelemetry(legacy, sizeof(legacy), false, telemetry, error));
  assert(error == owab::PARSE_LEGACY_DISABLED);
  assert(owab::parseTelemetry(legacy, sizeof(legacy), true, telemetry, error));
  assert(telemetry.fields == owab::TELEMETRY_STATUS);
  assert(telemetry.status == 2);
}

static void testIntervalDueWraparound() {
  assert(owab::intervalDue(100, 0, 1000));
  assert(!owab::intervalDue(1500, 1000, 1000));
  assert(owab::intervalDue(2000, 1000, 1000));
  assert(owab::intervalDue(25, UINT32_MAX - 50, 70));
}

int main() {
  testCrcVector();
  testDescriptorValidation();
  testExplicitCrcFailures();
  testDescriptorRejectsTelemetryAndBadBounds();
  testDescriptorRejectsInvalidUtf8();
  testFramedTelemetryAllowlist();
  testPartialTelemetryAndSequenceWrap();
  testAllFrameLengthsAndDeterministicInput();
  testLegacyTelemetryPolicy();
  testIntervalDueWraparound();
  puts("onewire accessory protocol tests passed");
  return 0;
}
// AI: end
