#!/usr/bin/env node
'use strict';

// AI: below smoke test was generated by an AI
const assert = require('node:assert/strict');

function usage() {
  console.error('Usage: node usermods/onewire_accessory_bus/smoke-test.js http://wled-ip [expected-rom]');
  console.error('Set OWAB_ALLOW_EMPTY=1 for an intentional no-accessory test and OWAB_SETTINGS_PIN when required.');
  process.exit(2);
}

const baseUrl = process.argv[2];
const expectedRom = process.argv[3] ? process.argv[3].toUpperCase() : '';
const allowEmpty = process.env.OWAB_ALLOW_EMPTY === '1';
const settingsPin = process.env.OWAB_SETTINGS_PIN || '';
const timeoutMs = Number(process.env.OWAB_SMOKE_TIMEOUT_MS || 30000);
if (!baseUrl || (!expectedRom && !allowEmpty) || !Number.isFinite(timeoutMs) || timeoutMs < 1000) usage();
if (Number(process.versions.node.split('.')[0]) < 18) throw new Error('Node.js 18 or newer is required for fetch()');

const sleep = milliseconds => new Promise(resolve => setTimeout(resolve, milliseconds));

async function fetchJson(path, options = {}) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 7000);
  try {
    const response = await fetch(new URL(path, baseUrl), { ...options, signal: controller.signal });
    assert.equal(response.ok, true, `${path} returned HTTP ${response.status}`);
    return await response.json();
  } finally {
    clearTimeout(timer);
  }
}

async function postState(payload) {
  const body = { v: true, OneWireAccessory: payload };
  if (settingsPin) body.pin = settingsPin;
  return await fetchJson('/json/state', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body)
  });
}

function validateState(state) {
  const ow = state.OneWireAccessory;
  assert.ok(ow, 'OneWireAccessory object missing from /json/state');
  assert.equal(typeof ow.deviceCount, 'number', 'deviceCount must be numeric');
  assert.ok(Array.isArray(ow.devices), 'devices must be an array');
  assert.ok(Array.isArray(ow.deviceDetails), 'deviceDetails must be an array');
  assert.ok(Array.isArray(ow.profiles), 'profiles must be an array');
  assert.equal(typeof ow.busHealth, 'string', 'busHealth must be a string');
  return ow;
}

(async () => {
  validateState(await fetchJson('/json/state'));
  const infoBefore = await fetchJson('/json/info');
  assert.ok(infoBefore.onewire, 'onewire object missing from /json/info');
  const initialScanCount = infoBefore.onewire.scanCount;
  assert.equal(typeof initialScanCount, 'number', 'info.onewire.scanCount must be numeric');

  const commandState = validateState(await postState({ scan: true }));
  assert.equal(commandState.commandCode, 'ok', commandState.commandMessage || 'manual scan command failed');

  const deadline = Date.now() + timeoutMs;
  let owAfter;
  let infoAfter;
  while (Date.now() < deadline) {
    await sleep(500);
    const state = await fetchJson('/json/state');
    owAfter = validateState(state);
    infoAfter = await fetchJson('/json/info');
    const scanned = infoAfter.onewire && infoAfter.onewire.scanCount > initialScanCount;
    const expectedDetected = !expectedRom
      || owAfter.devices.map(rom => String(rom).toUpperCase()).includes(expectedRom);
    const emptyStable = allowEmpty && owAfter.busStateKnown && owAfter.busHealth === 'empty_clean';
    if (scanned && (expectedDetected || emptyStable)) break;
  }

  assert.ok(infoAfter.onewire.scanCount > initialScanCount, 'scanCount did not advance before timeout');
  if (expectedRom) {
    assert.ok(
      owAfter.devices.map(rom => String(rom).toUpperCase()).includes(expectedRom),
      `expected ROM ${expectedRom} was not detected after a fresh stable scan`
    );
    assert.equal(owAfter.busHealth, 'devices', 'bus health must report devices');
  } else {
    assert.equal(owAfter.busHealth, 'empty_clean', 'empty-bus smoke test did not reach a stable clean state');
  }

  assert.equal(typeof owAfter.applyStatus, 'string', 'applyStatus must be a string');
  assert.equal(typeof owAfter.inputStatus, 'string', 'inputStatus must be a string');
  assert.equal(typeof infoAfter.onewire.crcErrors, 'number', 'info.onewire.crcErrors must be numeric');

  console.log(JSON.stringify({
    ok: true,
    deviceCount: owAfter.deviceCount,
    devices: owAfter.devices,
    busHealth: owAfter.busHealth,
    activeProfile: owAfter.activeProfile,
    applyStatus: owAfter.applyStatus,
    inputStatus: owAfter.inputStatus,
    scanCount: infoAfter.onewire.scanCount,
    crcErrors: infoAfter.onewire.crcErrors
  }, null, 2));
})().catch(error => {
  console.error(error && error.stack ? error.stack : String(error));
  process.exit(1);
});
// AI: end
