'use strict';

const assert = require('node:assert/strict');
const { describe, it } = require('node:test');
const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const repositoryRoot = path.resolve(__dirname, '..');
const githubWorkflow = fs.readFileSync(path.join(repositoryRoot, '.github', 'workflows', 'ci.yml'), 'utf8');
const forgejoWorkflow = fs.readFileSync(path.join(repositoryRoot, '.forgejo', 'workflows', 'ci.yml'), 'utf8');

// AI: below section was generated by an AI
describe('Release workflow contracts', () => {
  it('rejects invalid release evidence in executable packaging tests', () => {
    const run = spawnSync('python3', [path.join(repositoryRoot, 'tools', 'package_release.test.py')], {
      encoding: 'utf8'
    });
    assert.equal(run.status, 0, run.stderr || run.stdout);
    assert.match(run.stderr + run.stdout, /OK/);
  });

  it('captures PlatformIO metadata before the release build', () => {
    for (const workflow of [githubWorkflow, forgejoWorkflow]) {
      const metadata = workflow.indexOf('Record resolved PlatformIO metadata');
      const build = workflow.indexOf('Build ESP32 AudioReactive integration');
      const restore = workflow.indexOf('Restore validated PlatformIO metadata');
      const packaging = workflow.indexOf('Verify deterministic release packaging');
      assert.notEqual(metadata, -1);
      assert.notEqual(build, -1);
      assert.notEqual(restore, -1);
      assert.notEqual(packaging, -1);
      assert.ok(metadata < build, 'metadata generation must not remove completed build artifacts');
      assert.ok(build < restore, 'validated metadata must be restored after the firmware build');
      assert.ok(restore < packaging, 'packaging must consume restored validated metadata');
      assert.ok(build < packaging, 'packaging must run after the firmware build');
      assert.match(workflow, /--json-output-path/);
      assert.match(workflow, /RUNNER_TEMP\/owab-platformio-metadata\.json/);
      assert.match(workflow, /json\.load\(open\(sys\.argv\[1\]\)\)/);
    }
  });

  it('rejects personal commit and annotated-tag email metadata', () => {
    for (const workflow of [githubWorkflow, forgejoWorkflow]) {
      assert.match(workflow, /git log --all --format='%ae%n%ce'/);
      assert.match(workflow, /git for-each-ref refs\/tags --format='%\(taggeremail\)'/);
      assert.match(workflow, /users\\\.noreply\\\.github\\\.com/);
      assert.match(workflow, /Non-noreply commit identity found in public history/);
      assert.match(workflow, /Non-noreply annotated-tag identity found in public history/);
    }
  });

  it('pins GitHub provenance and SBOM attestations for release artifacts', () => {
    assert.match(githubWorkflow, /id-token: write/);
    assert.match(githubWorkflow, /attestations: write/);
    assert.match(githubWorkflow, /artifact-metadata: write/);
    assert.equal((githubWorkflow.match(/actions\/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6/g) || []).length, 2);
    assert.match(githubWorkflow, /subject-path: WLED\/\.pio\/build\/esp32dev_onewire_audio\/firmware\.bin/);
    assert.match(githubWorkflow, /sbom-path: WLED\/owab\.spdx\.json/);
  });

  it('targets the available Forgejo runner with compatible pinned tools', () => {
    assert.match(forgejoWorkflow, /runs-on: macos-latest/);
    assert.match(forgejoWorkflow, /timeout-minutes: 30/);
    assert.match(forgejoWorkflow, /FORGEJO_UV/);
    assert.doesNotMatch(forgejoWorkflow, /actions\/upload-artifact/);
    assert.match(forgejoWorkflow, /Verify local candidate evidence/);
    assert.match(forgejoWorkflow, /release-package\/SHA256SUMS/);
    assert.match(forgejoWorkflow, /shasum -a 256 --check SHA256SUMS/);
    assert.match(forgejoWorkflow, /SYFT_VERSION: 1\.42\.3/);
    assert.match(forgejoWorkflow, /SYFT_DARWIN_AMD64_SHA256: c00d01b7c43504708c8922d643d1cbaefa62ca8876baa4d2c2cf4c3be43707a9/);
    assert.match(forgejoWorkflow, /syft_\$\{SYFT_VERSION\}_darwin_amd64\.tar\.gz/);
    assert.match(forgejoWorkflow, /--connect-timeout 15 --max-time 180/);
    assert.match(forgejoWorkflow, /--retry 3 --retry-all-errors/);
    assert.match(forgejoWorkflow, /shasum -a 256 --check/);
    assert.match(forgejoWorkflow, /scan dir:WLED -o spdx-json=WLED\/owab\.spdx\.json/);
    assert.doesNotMatch(forgejoWorkflow, /anchore\/sbom-action/);
    assert.doesNotMatch(forgejoWorkflow, /^\s*uses:\s+(?!https:\/\/github\.com\/)/m);
  });
});
// AI: end
